name: Build, Push to DockerHub, Deploy to AWS EC2

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build WAR using Maven
        run: mvn -B package --file pom.xml

      # Install Sonar Scanner
      - name: Install Sonar Scanner
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-5.0.1.3006.zip
          unzip sonar-scanner-5.0.1.3006.zip
          sudo mv sonar-scanner-5.0.1.3006 /opt/sonar-scanner


    # Run SonarQube Scan
      - name: SonarQube Scan
        run: |
          ./sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=ecom_demo \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # 2. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ecom_demo:latest .

      # 4. Push Docker image to DockerHub
      # update the dockerhub key previliges
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecom_demo:latest

      # 5. Deploy on AWS EC2 via SSH
      - name: Deploy on AWS EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ecom_demo:latest

            echo "Stopping old container..."
            docker stop myapp || true
            docker rm myapp || true

            echo "Starting new container..."
            docker run -d -p 8080:8080 --name myapp ${{ secrets.DOCKERHUB_USERNAME }}/ecom_demo:latest

            echo "Deployment Complete!"
