name: Build, Push Docker, Deploy to GCP VM

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ---- DockerHub Login ----
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- Build Docker Image ----
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ecom_demo:latest .

      # ---- Push Image to DockerHub ----
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecom_demo:latest

      # ---- Deploy to GCP VM ----
      - name: Deploy on GCP VM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ecom_demo:latest

            echo "Stopping old container if running..."
            docker stop myapp || true
            docker rm myapp || true

            echo "Starting new container..."
            docker run -d -p 80:80 --name ecom_demo ${{ secrets.DOCKERHUB_USERNAME }}/ecom_demo:latest

            echo "Deployment Completed Successfully!"

